### ISSUE TITLE
libastroidapp1 missing

### ISSUE THREAD

**Issue by jonathf** [MagneFire/asteroid-2048#4]
I installed the app using the instruction [you provided on twitter](https://twitter.com/MagneFire_/status/1295050029703532547). I tried to install on my Huawei Watch with the newest AstroidOS, but got the error:
```
sh-5.0# opkg install asteroid-2048_+git0+647fdca347-r1_armv7vehf-neon.ipk

Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - conflicting requests
 *   - nothing provides libasteroidapp1 >= +git0+c4b13aabf9 needed by asteroid-2048-+git0+647fdca347-r1.armv7vehf-neon
 *
 * Solution 1:
 *   - do not ask to install asteroid-2048-+git0+647fdca347-r1.armv7vehf-neon
```

Anything I need to do to get the app working?

**Comment by MagneFire** [comment]
Thanks for the heads up :+1: 

It seems that the ipk that I provided depends on some outdated packages. I will rebuild the package once the new nightlies are up.
Meanwhile you should be able to install the app by adding the `--force-depends` flag. So the install command will become:
```
opkg install --force-depends asteroid-2048_+git0+647fdca347-r1_armv7vehf-neon.ipk
```

**Comment by jonathf** [comment]
Thanks for the quick response.

That solves the install process. The app shows up in the menu, but pressing it does not result in the app launching. It just lingers until the display falls asleep.

**Comment by MagneFire** [comment]
Hmm, ok, it seems that the current nightly might be even newer then.
Can you try to install the ipk below?
https://www.dropbox.com/s/oplpsn474b9q00e/asteroid-2048_%2Bgit0%2B0aeb78c95d-r1_armv7vehf-neon.ipk?dl=0

This is for the very latest nightly that might still be compiling on the nightly build server. But it's worth a shot.

If neither work, can you provide a `journalctl --no-pager` log?

**Comment by jonathf** [comment]
That did the trick. Thanks for your help. It is very much appriciated.
